const {chromium}=await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const baseURL=process.env.BASE_URL||'http://localhost:5173';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
await mkdir('artifacts',{recursive:true});
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[],externalRequests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',req=>{if(new URL(req.url()).origin!==new URL(baseURL).origin)externalRequests.push(new URL(req.url()).origin);});
const entry=await page.request.get(baseURL);
assert.equal(entry.status(),200);
assert.match(entry.headers()['content-security-policy'],/default-src 'self'/);
for(const exposed of ['/README.md','/package.json','/.git/config','/tests/scoring.test.mjs','/../../etc/passwd','/%2e%2e/README.md'])assert.equal((await page.request.get(new URL(exposed,baseURL).href)).status(),404,`Unexpectedly served ${exposed}`);
await page.goto(baseURL);await page.getByRole('heading',{name:'Choose your practice set'}).waitFor();
const styleResponse=await page.request.get(new URL('/src/style.css',baseURL).href);
assert.equal(styleResponse.status(),200);assert.match(styleResponse.headers()['content-type'],/text\/css/);
assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).backgroundColor),'rgb(247, 248, 245)');
await page.screenshot({path:'artifacts/home-desktop.png',fullPage:true});
assert.equal(await page.locator('.set-row').count(),5);
const source=await (await page.request.get(`${baseURL}/public/questions.json`)).json();
await page.locator('[data-set="0"]').click();
assert.equal(await page.locator('.q-number').count(),90);
const firstPdfId=Number((await page.locator('.question-bottom > span').innerText()).match(/\d+/)[0]);
const firstQuestion=source.find(q=>q.id===firstPdfId);
for(const id of firstQuestion.correct)await page.locator(`input[value="${id}"]`).check();
await page.getByRole('button',{name:'Flag for review',exact:true}).click();
assert.ok(await page.locator('.q-number').first().evaluate(e=>e.classList.contains('answered')&&e.classList.contains('flagged')));
await page.getByRole('button',{name:'Next question',exact:true}).click();
const secondPdfId=Number((await page.locator('.question-bottom > span').innerText()).match(/\d+/)[0]);
const secondQuestion=source.find(q=>q.id===secondPdfId);
const deliberatelyWrong=secondQuestion.correct.length>1?[secondQuestion.correct[0]]:[secondQuestion.options.find(o=>!secondQuestion.correct.includes(o.id)).id];
for(const id of deliberatelyWrong)await page.locator(`input[value="${id}"]`).check();
await page.reload();await page.locator('[data-set="0"]').click();
for(const id of deliberatelyWrong)assert.ok(await page.locator(`input[value="${id}"]`).isChecked());
await page.screenshot({path:'artifacts/test-desktop.png',fullPage:true});
await page.getByRole('button',{name:'Submit test',exact:true}).click();
await page.getByRole('button',{name:'Keep practicing',exact:true}).click();
await page.getByRole('button',{name:'Submit test',exact:true}).click();
await page.locator('dialog').getByRole('button',{name:'Submit test',exact:true}).click();
await page.getByRole('heading',{name:'Your results',exact:true}).waitFor();
assert.match(await page.locator('.score-value').innerText(),/1 of 90 correct/);
assert.match(await page.locator('.score-breakdown').innerText(),/88\s*Unanswered/);
assert.match(await page.locator('.scaled-score').innerText(),/10\s*\/ 900/);
await page.locator('.q-number').first().click();
await page.locator('.explanation').waitFor();
assert.equal(await page.locator('.right-answer').count(),firstQuestion.correct.length);
await page.screenshot({path:'artifacts/review-desktop.png',fullPage:true});
await page.locator('[data-filter="incorrect"]').click();assert.equal(await page.locator('.review-item').count(),1);
await page.locator('[data-filter="unanswered"]').click();assert.equal(await page.locator('.review-item').count(),88);
await page.setViewportSize({width:390,height:844});
await page.locator('.brand').click();await page.screenshot({path:'artifacts/home-mobile.png',fullPage:true});
await page.locator('[data-set="4"]').click();assert.equal(await page.locator('.q-number').count(),54);
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.screenshot({path:'artifacts/test-mobile.png',fullPage:true});
await page.getByRole('button',{name:'Submit test',exact:true}).click();await page.locator('dialog').getByRole('button',{name:'Submit test',exact:true}).click();
await page.locator('.q-number').first().click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.screenshot({path:'artifacts/review-mobile.png',fullPage:true});
await page.getByRole('button',{name:'Retake set',exact:true}).click();
await page.getByRole('button',{name:'Keep results',exact:true}).click();
await page.getByRole('heading',{name:'Your results',exact:true}).waitFor();
await page.getByRole('button',{name:'Retake set',exact:true}).click();
await page.getByRole('button',{name:'Start again',exact:true}).click();
assert.equal(await page.locator('input:checked').count(),0);
const multiPage=await browser.newPage({viewport:{width:1440,height:1000}});
multiPage.on('pageerror',e=>errors.push(e.message));
multiPage.on('request',req=>{if(new URL(req.url()).origin!==new URL(baseURL).origin)externalRequests.push(new URL(req.url()).origin);});
await multiPage.goto(baseURL);await multiPage.locator('[data-set="0"]').click();
const multi=source.slice(0,90).find(q=>q.correct.length>1);
const questionOrder=JSON.parse(await multiPage.evaluate(()=>localStorage.getItem('security-practice-v1')))[0].questionOrder;
let multiIndex=-1;
for(let i=0;i<90;i++){
 await multiPage.locator(`[data-action="jump"][data-index="${i}"]`).click();
 const visibleId=Number((await multiPage.locator('.question-bottom > span').innerText()).match(/\d+/)[0]);
 assert.equal(questionOrder[i],visibleId,'Saved order matches the displayed question order');
 if(visibleId===multi.id){multiIndex=i;break;}
}
assert.notEqual(multiIndex,-1);
assert.equal(await multiPage.locator('input[type="checkbox"]').count(),multi.options.length);
for(const id of multi.correct)await multiPage.locator(`input[value="${id}"]`).check();
await multiPage.getByRole('button',{name:'Submit test',exact:true}).click();
await multiPage.locator('dialog').getByRole('button',{name:'Submit test',exact:true}).click();
assert.match(await multiPage.locator('.score-value').innerText(),/1 of 90 correct/);
await multiPage.locator(`[data-action="jump"][data-index="${multiIndex}"]`).click();
assert.equal(await multiPage.locator('.right-answer').count(),multi.correct.length);
assert.match(await multiPage.locator('.review-options .option-letter').first().innerText(),/A/);
await multiPage.reload();await multiPage.locator('[data-set="0"]').click();
assert.match(await multiPage.locator('.score-value').innerText(),/1 of 90 correct/);
await multiPage.close();
assert.deepEqual(errors,[]);assert.deepEqual(externalRequests,[]);
await browser.close();console.log('Browser checks passed: set selection, answers, flags, persistence, submission, score, filters, expanded explanations, 54-question final set, mobile overflow, server headers and file exposure.');
